title: Blog about nothing in particular
author: Kirstin
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Well just seeing if I can learn something new.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
